trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '18.x'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Static Web App'
  inputs:
    app_location: '/'           # Root of your app (change if your app is in a subfolder)
    output_location: 'build'    # React's build output folder
    azure_static_web_apps_api_token: $(deployment_token) # Set this as a secret variable in your pipeline
